import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  appContainer: { flex: 1, backgroundColor: "#8b63c3", padding: 20 },
  title: { fontSize: 30, color: "white", fontWeight: "bold", marginBottom: 15 },
  navButtons: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-around",
    marginBottom: 15,
  },
  navBtn: {
    backgroundColor: "#d3248b",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginVertical: 4,
  },
  navBtnText: { color: "black", fontWeight: "bold" },
  searchInput: {
    backgroundColor: "#d572b4",
    borderRadius: 20,
    padding: 8,
    fontWeight: "bold",
    marginBottom: 10,
  },
  menuCard: {
    backgroundColor: "#3c225f",
    borderRadius: 20,
    padding: 15,
    marginBottom: 10,
  },
  menuTitle: { color: "#ff7fe0", fontSize: 18, fontWeight: "bold" },
  menuText: { color: "#ffd6f3", fontSize: 14, marginVertical: 2 },
  removeBtn: {
    backgroundColor: "#ff5fb3",
    padding: 6,
    borderRadius: 10,
    marginTop: 6,
    alignSelf: "center",
  },
  removeBtnText: { color: "black", fontWeight: "bold" },
  sectionTitle: {
    textAlign: "center",
    fontSize: 22,
    color: "#3b005a",
    fontWeight: "bold",
    marginTop: 10,
  },
  centerText: { textAlign: "center", color: "black", marginVertical: 10 },
  profileSection: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f2b8e2",
    padding: 10,
    borderRadius: 15,
    marginTop: 10,
  },
  profilePhoto: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#3c225f",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  formContainer: {
    backgroundColor: "#f2b8e2",
    padding: 15,
    borderRadius: 15,
    marginTop: 15,
  },
  label: { color: "#3b005a", fontWeight: "bold" },
  input: {
    backgroundColor: "#ffe6f7",
    borderRadius: 10,
    padding: 8,
    marginBottom: 8,
  },
  addBtn: {
    backgroundColor: "#d3248b",
    borderRadius: 15,
    padding: 10,
    alignItems: "center",
    marginTop: 10,
  },
  addBtnText: { color: "white", fontWeight: "bold" },
  nextPageBtn: {
    backgroundColor: "#d3248b",
    borderRadius: 15,
    padding: 10,
    alignItems: "center",
    marginVertical: 15,
  },
  nextPageText: { color: "black", fontWeight: "bold" },
  welcome: {
    textAlign: "center",
    fontSize: 18,
    fontWeight: "bold",
    color: "#3b005a",
    marginBottom: 10,
  },
});

export default styles;